before_script:
- npm install -g grunt-cli
language: node_js
node_js:
- 0.8
notifications:
  email: false
env:
  global:
    secure: QRElylTx997zMBpLk/z4aWaYzzULCTkqYuBfYY2wTC0GBoh2RLkRT5Cw+OeHZH9xhjq4EAxdOntK8O+8FAljPYqNEATvzJoD/qCoaRf/gMAQouA3eMJU/PFVsJnUP2O/GmF0i3OM6x3nBzCVch/NCld1hkM5fykngfPGPthpwOA=
