language: node_js
node_js:
    - 0.8
notifications:
    email: false
env:
    - [
        {secure: "Xw56jcIwXXbUQOFvklXUxlzTwfG4WP1NvMSwYX+RPkGI0aRgWQIXziA89rxI\n4ej5uupSgyH0RW8THHZYfzCaWDOMx6iemDJUBn0wjxJzw/HcRFz8spNi7m92\nFIOcVREPKEHoz/E6h70Gux1cd90RZXiTHdzQyj6mG62h4q2mFLI="}
    ]